name: Test

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Test
        run: pnpm t